language: c

dist:
  -focal

matrix:
  include:
    - os: linux
      dist: Xenial
      arch: amd64
      compiler: gcc
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Release
        - sanitizer=-DUSE_ASAN=ON

    - os: linux
      arch: amd64
      compiler: gcc
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Debug
        - sanitizer=-DUSE_ASAN=ON

    - os: linux
      arch: amd64
      compiler: gcc
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Release
        - sanitizer=-DUSE_ASAN=ON

    - os: linux
      arch: amd64
      compiler: clang
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Release
        - sanitizer=-DUSE_ASAN=ON

    # - os: linux
    #   arch: amd64
    #   compiler: clang
    #   env: 
    #     - buildtype=-DCMAKE_BUILD_TYPE=Debug
    #     - sanitizer=-DUSE_MSAN=ON

    # - os: linux
    #   arch: amd64
    #   compiler: clang
    #   env: 
    #     - buildtype=-DCMAKE_BUILD_TYPE=Release
    #     - sanitizer=-DUSE_MSAN=ON

    - os: linux
      addons:
        apt:
          packages:
            - binutils-mingw-w64
            - gcc-mingw-w64
      compiler: x86_64-w64-mingw32-gcc
      env: 
        - CROSS=1
        - toolchain=-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/x86_64-windows-mingw64.cmake
        - buildtype=-DCMAKE_BUILD_TYPE=Release

    - os: osx
      arch: amd64
      compiler: gcc
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Release
        - sanitizer=-DUSE_ASAN=ON

    - os: osx
      arch: amd64
      osx_image: xcode10.2
      compiler: clang
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Debug
        - sanitizer=-DUSE_ASAN=ON

    - os: osx
      arch: amd64
      osx_image: xcode11.1
      compiler: clang
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Release
        - sanitizer=-DUSE_ASAN=ON

    # - os: linux
    #   arch: amd64
    #   addons:
    #     apt:
    #       packages:
    #         - gcc-aarch64-linux-gnu
    #   compiler: aarch64-linux-gnu-gcc
    #   env: 
    #     - CROSS=1
    #     - toolchain=-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/aarch64-linux-gcc.cmake
    #     - buildtype=-DCMAKE_BUILD_TYPE=Release

    - os: linux
      arch: arm64
      compiler: gcc
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Release
        - sanitizer=-DUSE_ASAN=ON

    - os: linux
      arch: arm64
      compiler: clang
      env: 
        - buildtype=-DCMAKE_BUILD_TYPE=Release
        - sanitizer=-DUSE_ASAN=ON

script:
  - mkdir build
  - cd build
  - cmake $toolchain $buildtype $sanitizer ..
  - make VERBOSE=1
  - if [ -z "$CROSS" ]; then make test; fi

# after_failure:
#   - cat /Users/travis/build/piggypiggy/fp256/build/CMakeFiles/CMakeOutput.log
#   - cat /Users/travis/build/piggypiggy/fp256/build/CMakeFiles/CMakeError.log