name: x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {
            name: "x64-ubuntu18.04-gcc debug",
            arch: x64,
            os: ubuntu-18.04,
            cc: gcc,
            build_type: Debug
          }
        - {
            name: "x64-ubuntu18.04-gcc release",
            arch: x64,
            os: ubuntu-18.04,
            cc: gcc,
            build_type: Release
          }
        - {
            name: "x64-ubuntu18.04-clang release",
            arch: x64,
            os: ubuntu-18.04,
            cc: clang,
            build_type: Release
          }
        - {
            name: "x64-macos10.15-gcc release",
            arch: x64,
            os: macos-10.15,
            cc: gcc,
            build_type: Release
          }
        - {
            name: "x64-macos10.15-clang release",
            arch: x64,
            os: macos-10.15,
            cc: clang,
            build_type: Release
          }

    steps:
      - uses: actions/checkout@v2

      - name: configure
        env:
          CC: ${{matrix.config.cc}}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DUSE_ASAN=ON

      - name: build
        run: cd build && make -j VERBOSE=1
      
      - name: test
        run: cd build && make test
